#!/bin/bash

function check(){
local OPTIND opt i
while getopts ":p:" opt; do
    case $opt in
        p)
#print out the lines from the srt file with lyrics and exit
            sed -n '/^..:..:..,... --> ..:..:..,...$/,/^$/{//!p}' $2
            exit 1
;;
    esac
done
shift $((OPTIND-1))
}

check $@

#turn the comma into a colon, so that I can use a colon as a field delimiter with awk
paste <(grep ^..:.. $1 | sed 's/,/\:/g' |

while read line
do
#Get the timestamps and then convert the HH:MM:SS format into seconds.
begtime=$(grep -o ^..:..:..:... <(echo $line) | awk -F: '{print ($1 * 3600 + $2 * 60 + $3 + $4 / 1000)}')

endtime=$(grep -o ..:..:..:...$ <(echo $line) | awk -F: '{print ($1 * 3600 + $2 * 60 + $3 + $4 / 1000)}') 

wait=$(echo $endtime - $begtime | bc -l)

echo $wait
done) <(sed -n '/^..:..:..,... --> ..:..:..,...$/,/^$/{//!p}' $1) |

while read line
do
echo $line | awk -F' ' '{$1=""; print $0}'    

time=$(awk -F' ' '{print $1}' <(echo $line))
sleep $time

done


 
