#!/bin/bash

function check(){
local OPTIND opt i
while getopts ":p:" opt; do
    case $opt in
        p)
#print out the lines from the srt file with lyrics and exit
            sed -n '/^..:..:..,... --> ..:..:..,...$/,/^$/{//!p}' $2
            exit 1
;;
    esac
done
shift $((OPTIND-1))
}

check $@

paste <(grep ^..:.. $1 | sed 's/,/\:/g' |

while read line
do
begstamp=$(grep -o ^..:..:..:... <(echo $line))
begtime=$(echo $begstamp | awk -F: '{print ($1 * 3600 + $2 * 60 + $3 + $4 / 1000)}')

endstamp=$(grep -o ..:..:..:...$ <(echo $line))
endtime=$(echo $endstamp | awk -F: '{print ($1 * 3600 + $2 * 60 + $3 + $4 / 1000)}') 

wait=$(echo $endtime - $begtime | bc -l)

echo $wait
done) <(sed -n '/^..:..:..,... --> ..:..:..,...$/,/^$/{//!p}' $1) |

while read line
do
echo $line | awk -F' ' '{$1=""; print $0}'    

time=$(echo $line | awk -F' ' '{print $1}')
sleep $time

done


 
